/*!
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya
\copyright	2023- Shun Moriya
All Rights Reserved.
*/
#pragma once
#define DUNGENERATOR_PLUGIN_FILE_VERSION "3"
#define DUNGENERATOR_PLUGIN_VERSION "1"
#define DUNGENERATOR_PLUGIN_VERSION_NAME "1.0"
#define DUNGENERATOR_PLUGIN_FRIENDLY_NAME "VoicevoxPlayer"
#define DUNGENERATOR_PLUGIN_DESCRIPTION "Voicevox Player"
#define DUNGENERATOR_PLUGIN_DOCS_URL "https://github.com/shun126/VoicevoxPlayer/wiki/"
#define DUNGENERATOR_PLUGIN_SUPPORT_URL "https://github.com/shun126/VoicevoxPlayer/discussions/"
#define DUNGENERATOR_PLUGIN_BETA_VERSION "true"
